### PR TITLE
#444: Removed pipes dependency

### PR DESCRIPTION
**Pull request by BasedDepartment1**

### CODE REVIEW

**Review by Borda — APPROVED** [review]

**Review by hauntsaninja — APPROVED** [review]
Thanks, would be great for this to get merged!

**Comment by Borda** [comment]
cc: @dbieber

**Comment by thilomichael** [comment]
I would very much like for this to be merged, as the current v0.5.0 results in deprecation warnings due to the pipe dependency :)

**Comment by dbieber** [comment]
Noted! It's been a while since we've had updates or a release. I think I can likely make time to do one before the end of the year.

**Comment by dbieber** [comment]
I realize we are now past the end of the year. Apologies.

**Comment by wickeat** [comment]
Seems like this didn't make it in time for the v0.6.0 release. :(

**Comment by sspans-sbp** [comment]
@dbieber this is now broken on Python 3.13 (released today).

Any chance of doing a new release with this issue fixed?

**Comment by dbieber** [comment]
Thanks for the heads up, yes I will update here once released, and will prioritize doing so shortly.

**Comment by dbieber** [comment]
The 0.7.0 release is now on pypi. https://pypi.org/project/fire/0.7.0/

**Pull request merged**
