### PR TITLE
PEP8 changes

### PR DESCRIPTION
**Pull request by rahulkp220**
Improved the Pylint score.

### CODE REVIEW

**Comment by rahulkp220** [comment]
I signed it!

**Comment by waldyrious** [comment]
For convenience, note that this diff is much easier to review in ignore-whitespace mode: https://github.com/google/python-fire/pull/23/files?diff=split&w=1

**Comment by dbieber** [comment]
Thanks for your contribution. While I'm open to style changes, it's important that we remain stylistically consistent across the project.

For now we're following the internal Google Python style guide. The most notable difference from the [external one](https://google.github.io/styleguide/pyguide.html) is that it permits capital-letter FunctionNames. While I would like to switch to a public style guide, it's important that we maintain consistency within the project and also that we maintain the bare-minimum level of backwards compatibility (i.e. exposing a function named `Fire`).

Let's hold off on any widespread style changes until I figure out how to release the pylintrc that we're using internally.

**Comment by rahulkp220** [comment]
Ohkay sure. I agree with you on the point of consistency across the project.

**Pull request closed without merging**
