### PR TITLE
Add conda forge

### PR DESCRIPTION
**Pull request by CJ-Wright**
The recipe hasn't been accepted yet, but it should be soon.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@googlebot I signed it!

**Comment by CJ-Wright** [comment]
The package is up on conda!

**Comment by dbieber** [comment]
Good to hear :).

I'm not too familiar with conda. What does the '-c conda-forge' indicate? Is that standard for installing packages or can we whittle it down to just 'conda install fire'?

**Comment by CJ-Wright** [comment]
Conda has channels so that you can pull packages from different places, `-c conda-forge` specifies to use the conda-forge channel. You can set it as a default in your `.condarc` which is usually a good default. `conda install fire` most likely won't work unless you have set conda-forge as a default.

**Comment by CJ-Wright** [comment]
Can I get a merge?

**Comment by dbieber** [comment]
Hey heads up that we'll be including these conda install instructions into the docs soon. Apologies for the delay.

**Comment by CJ-Wright** [comment]
Thank you!
Please let me know if/when you update to a new version so I can update the conda version as well.

**Comment by dbieber** [comment]
Will do.

**Comment by dbieber** [comment]
@CJ-Wright could you please update the conda version?

**Comment by CJ-Wright** [comment]
Already done https://github.com/conda-forge/fire-feedstock/pull/10

**Pull request merged**
