### PR TITLE
grouping has output

### LINKED ISSUE #240: example in docs for grouping has no output
Hello, following the docs here: https://github.com/google/python-fire/blob/master/docs/guide.md#grouping-commands

I am unable to get this to run when calling 

```python
example.py run
```

It currently returns no output.

If I run either of the `digestion run` or `ingestion run` commands they work flawlessly just not the grouped command 

Heres the code:

```python
import fire

class IngestionStage(object):

  def run(self):
    return 'Ingesting! Nom nom nom...'

class DigestionStage(object):

  def run(self, volume=1):
    return ' '.join(['Burp!'] * volume)

  def status(self):
    return 'Satiated.'

class Pipeline(object):

  def __init__(self):
    self.ingestion = IngestionStage()
    self.digestion = DigestionStage()

  def run(self):
    self.ingestion.run()
    self.digestion.run()

if __name__ == '__main__':
  fire.Fire(Pipeline)
```

### PR DESCRIPTION
**Pull request by rajpratyush**
added the return statement at the end of run function in  pipeline class.

closes #240 

@dbieber can you please review it

### CODE REVIEW

**Comment by rajpratyush** [comment]
@googlebot I signed it!

**Comment by bencwallace** [comment]
Any reason this hasn't been merged? I spent a bit of time puzzling over this issue before finding this PR.

**Comment by rajpratyush** [comment]
I dont i asked for a review and no one reviewed it

**Comment by dbieber** [comment]
> Any reason this hasn't been merged? 

That's on me, I lost it behind some other notifications. So, thanks for commenting, bumping it back to the top. It's good to merge, and I will merge it at the next opportunity to do so.

**Comment by dbieber** [comment]
Merged in c1266d0dbb2114514fcf8be62044344b5a51c733

**Pull request merged**
