### PR TITLE
Pythonfire documentation

### LINKED ISSUE #69: Clearly document what python versions are supported (ie, python 3 support?)
Not seeing anything on the readme. Perhaps add [shields.io](https://shields.io) badges that are automatically generated from the pypi listing?

### PR DESCRIPTION
**Pull request by ajomadlabs**
Fixes #69 

## Workflow   

1. Created a virtual environment
2. Created a python programe `hello.py`
3. First ran this file using `Python 2.7`
4. Worked Fine.
5. Next ran the file using `Python 3.4, 3.5 and 3.6`
6. Worked Successfully
7. Next add the python versions badge in the `README.md`

@dbieber  @jtratner Correct me if I'm wrong

### CODE REVIEW

**Comment by dbieber** [comment]
lgtm
@ajomadlabs + @benpadiyara, can you confirm that you've signed the CLA to make the googlebot happy? I think it's complaining because there is an identical commit from @benpadiyara as well as one from yourself @ajomadlabs.

**Comment by ajomadlabs** [comment]
@dbieber I have signed the CLA. The initial commit was done by me but I didn't knew that my git was authenticated with @benpadiyara . I came to know only after I pushed the commit.

**Comment by ajomadlabs** [comment]
@dbieber Is is there anything more that I need to do in this

**Comment by dbieber** [comment]
Nope, you're all set! Thanks for tackling the issue.

**Pull request merged**
