### PR TITLE
Update installation. md

### PR DESCRIPTION
**Pull request by thegautamkumarjaiswal**
I am just adding small things , it will help people to understand python environment and they setup easily. If you like please merge it.

### CODE REVIEW

**Comment by thegautamkumarjaiswal** [comment]
Please explain me my fault with it.

**Comment by thegautamkumarjaiswal** [comment]
@googlebot I signed it!

**Comment by thegautamkumarjaiswal** [comment]
@googlebot  I signed it!

**Comment by dbieber** [comment]
Thanks for the submission. I'm not going to merge this at this time. The "google-api-python-client" parts of the instructions aren't relevant to fire.

**Pull request closed without merging**
