### PR TITLE
Disabled ASCII conversion in order to improve console output encoding…

### PR DESCRIPTION
**Pull request by atgiovannini**
Just found that strings have bad encodings while printing `_OneLineResult`, e.g: 

## Before

```python
>>> json.dumps(d)
>>> '{"ascii": "esto es ascii", "utf-8": "\\u00e9st\\u00e9 es \\u00f1as cpl\\u00e9ho\\u00b4\\u00e7"}'
```

## After

```python
>>> json.dumps(d, ensure_ascii=False)
>>> '{"ascii": "esto es ascii", "utf-8": "ésté es ñas cplého´ç"}'
```

**Note: tested  at Windows and Linux**

### CODE REVIEW

**Comment by atgiovannini** [comment]
@googlebot I signed it!

**Comment by dbieber** [comment]
Hi! Looking at your pull request, I see that zero files have changed. It looks like you made some initial commits, and then followed up with commits that revert those initial commits, leaving no changes in the end.

**Comment by atgiovannini** [comment]
Hi!, sorry for the unnecessary commits, it's my first pull-request on github. The actual change is a line in a file core.py line 258, as seen in the first commit https://github.com/google/python-fire/pull/87/commits/2f726a26371b79d96ebff7ec13b8902dc0f981ad


The next commits, was to pass the test, for innecesary change in helputils.py

**Comment by atgiovannini** [comment]
I signed it!

Un saludo, Aaron Giovannini

Enviado desde Correo para Windows 10

De: googlebot
Enviado: viernes, 21 de julio de 2017 15:01
Para: google/python-fire
CC: atgiovannini; Author
Asunto: Re: [google/python-fire] Disabled ASCII conversion in order to improve console output encoding… (#87)

Thanks for your pull request. It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
📝 Please visit https://cla.developers.google.com/ to sign.
Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

• If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check your existing CLA data and verify that your email is set on your git commits.
• If your company signed a CLA, they designated a Point of Contact who decides which employees are authorized to participate. You may need to contact the Point of Contact for your company and ask to be added to the group of authorized contributors. If you don't know who your Point of Contact is, direct the project maintainer to go/cla#troubleshoot.
• In order to pass this check, please resolve this problem and have the pull request author add another comment and the bot will run again.

**Comment by dbieber** [comment]
Okay,
Can you update the pull request so it has the changes that you're interested in? Currently it shows no net changes (it has commits, but it also has commits that undo those original commits).

[And don't worry about having too many commits; when a pull request gets accepted we typically squash it down to a single commit anyway.]

**Comment by atgiovannini** [comment]
Well,I roll back, and then rewrite the change, I think commit https://github.com/google/python-fire/pull/87/commits/8198c79e1f8d039a7a54fe7286164d75a4ded9e2 is the right one!

**Comment by dbieber** [comment]
Great!
Can you explain this change to me and what prompted you to make it?
I don't know enough about this json option to know offhand if setting it to False is always appropriate.

**Comment by atgiovannini** [comment]
I found that every time that any CLI fired printed any "string" content, it was not encoded properly. You can find an example of how it was looking at the first comment. Basically, any non-ascii encoded string is being encoded as ascii.

**Pull request merged**
