### PR TITLE
Proposal: Move all tests to `tests` directory

### PR DESCRIPTION
**Pull request by AaronCritchley**
It seems to be a common standard to contain all of the libs tests in a single directory, this PR moves all tests (and references to them) into a single folder in the root dir.

I've kept the examples and their tests in their original folders, I figure it's more useful to have the test with the example than have it mixed it with the libs tests.

Some of the more questionable changes here like re-ordering imports are courtesy of PyCharm, they are all harmless but if it's an issue happy to change them as needed.

Ran all tests locally and all are passing.

Repo's for reference on the 'standard':
https://github.com/kennethreitz/requests
https://github.com/jakubroztocil/httpie
https://github.com/pallets/flask

### CODE REVIEW

**Comment by AaronCritchley** [comment]
I signed it!

**Comment by AaronCritchley** [comment]
Unsure on how to correctly fix the errors we're seeing, I've not dealt with projects configured this way before. Happy to take any suggestions/advice you might have?

I've toyed around with setup.py locally and had some success with changing the way that the dependencies are structured, let me know if it's worth continuing looking into.

**Comment by AaronCritchley** [comment]
Hey @dbieber, does this need any changes or is it good to go? Happy to make more changes if needed 😄

**Comment by dbieber** [comment]
Apologies for the delay. There's more work to do on my end of things to support this change, so it may be a bit before I get around to it.

For some context, we maintain a separate version of the codebase internally and externally, and have some scripts to keep the codebases in sync. The internal and external versions have slightly different imports and directory structures, and we also have BUILD files internally. So, before we can merge this in we'll have to update the sync script and the BUILD files.

**Comment by AaronCritchley** [comment]
Let me know when you're good to go with this and I'll be happy to fix the merge conflicts that have come up, no rush though, just don't want to resolve them without it being needed :smile:

**Comment by dbieber** [comment]
Will do. I appreciate your patience.

**Comment by AaronCritchley** [comment]
Closing as stale - ping if you'd like me to reopen / fix conflicts

**Pull request closed without merging**
