### PR TITLE
use a custom getfullargspec that follows wrapped chains #159

### PR DESCRIPTION
**Pull request by vbarbaresi**
using complex decorators like @functools.lru_cache()
was breaking positional parameters handling

We used `inspect.getfullargspec()`, that ignores `__wrapped__` attributes for legacy reasons
It is based internally on `inspect.signature()` which allows following the chain of
`__wrapped__` attributes

I took the code from getfullargspec() and changed it to use
skip_bound_arg=True and follow_wrapper_chains=True

This fixes the lru_cache decorator usage and allows to remove
a line that was getting rid of the bound args.

This applies only to Python3, Python2 wasn't affected by this issue

### CODE REVIEW

**Comment by vbarbaresi** [comment]
I wasn't sure at first but it fixes #190 actually
But it needs `@functools.wraps(f)` to be able to follow the chain. I'll add a test

**Comment by dbieber** [comment]
Thanks a bundle for doing this. 

I always feel bad asking volunteers to do additional work, but if you're up for it, these are the change's we'll need to make:
- style stuff: 80 char line limit, 2 spaces for indent, 4 spaces for continuations, naming of custom_getfullargspec (I recommend GetFullArgSpecPy3), docstring for custom_getfullargspec (should be google-style, see other fns for examples)
- functools32 may provide an lru_cache that works in PY2 and PY3

Anything you don't get to I'll clean up when I accept the PR (which may be a bit, as I'm bottlenecked by other work at the moment.)

**Comment by vbarbaresi** [comment]
no problem, I can handle the style stuff

for functools32, I'm not sure where to add development dependencies.
It looks like they are only embedded as `pip install foo` in the Travis config file?

**Comment by dbieber** [comment]
Also as TEST_DEPENDENCIES in setup.py

**Comment by vbarbaresi** [comment]
I just realized that functools32 is only made for Python2 so it would be a bit cumbersome to have some Py2 dependencies only.

The bug didn't occur on Py2 with `functools32.lru_cache()` anyway so it may not be necessary to really test it

**Comment by dbieber** [comment]
OK, sgtm

**Comment by cmin764** [comment]
Can't wait for this to be accepted!

**Comment by dbieber** [comment]
I think we'll get this in shortly.

**Comment by dbieber** [comment]
Merged in deb33cc34f94cad86a875a9993864ac0acf93828

**Pull request closed without merging**
