### PR TITLE
Skip components we've already seen.

### PR DESCRIPTION
**Pull request by gaojiuli**
Inspired by built-in function `pkgutil.walk_packages()`

### CODE REVIEW

**Comment by dbieber** [comment]
Thanks for contributing!

I don't think this will produce the desired behavior though, since each call to _Commands will define it's own `seen` function with it's own `m`. Also the member_name is not sufficient to determine whether a component has been seen, since there can be different components with the same member_name.

For some context, one reason we would want to skip already seen components is to prevent an infinite loop when generating the completions (currently this is done via the `depth` parameter).

I went to prepare a minimal example:
```
import fire
x = {}
x['y'] = x
fire.Fire()
```
(but fire breaks on this because it tries to serialize x with json, which can't handle the circular reference :/)

So, here's a different small example:
```
import fire

class Sample(object):
  def __init__(self):
    self.prop = None

sample = Sample()
sample.prop = sample

fire.Fire()
```

`python example.py sample prop prop prop prop prop` is a perfectly valid command. But we don't want to run forever generating our completion script.
Maybe there's a change that we can make as part of #32 to allow for proper tab completion of this without an infinite length completion script :).

**Comment by gaojiuli** [comment]
I have done a  an experiment.

```python
def test(a, m={}):
    print(id(test))

    def seen(p):
        if p in m:
            return True
        m[p] = True
        print(id(seen))
        print(id(m))
        print(m)

    seen(a)

test(1)
test(2)
test(3)
test(3)
```

I get the result:

```
140318639763240
140318617455336
140318639562120
{1: True}
140318639763240
140318617455608
140318639562120
{1: True, 2: True}
140318639763240
140318617454792
140318639562120
{1: True, 2: True, 3: True}
140318639763240
```

The result shows that each call test has the same seen() and the same m. 
Different components with the same member_name. So we could use id(component) instead.

**Comment by dbieber** [comment]
> We could use id(component) instead.

Good thought.

Another thing we'll have to address is that we don't want "seen" to be a lifetime property of an object. Instead, we want to check whether we've seen an object before during the current top-level call to `_Commands`.

One way we might do this is with a `set` of ids and a helper function. Something like this:

```
def _Commands(component):
  seen = set()
  return _CommandsHelper(component, seen)
  
def _CommandsHelper(component, seen):
  seen.add(id(component))

  for member_name, member in _Members(component):
    if id(member) in seen:
      continue
    member_name = _FormatForCommand(member_name)
    yield (member_name,)
    
    if inspect.isroutine(member) or inspect.isclass(member):
      for completion in Completions(member):
        yield (member_name, completion)
      continue  # Don't descend into routines.
 
    for command in _CommandsHelper(member, seen):
      yield (member_name,) + command
  
  seen.remove(id(component))
```

**Comment by gaojiuli** [comment]
I tried this:

```python
def _Commands(component):
    seen = set()
    return _CommandsHelper(component, seen=seen)


def _CommandsHelper(component, seen):
    seen.add(id(component))
    print(id(seen), seen)


_Commands("1")
_Commands("2")

_Commands("1")
_Commands("2")

```

result:
```
139921437490312 {139921437069920}
139921437490312 {139921437070032}
139921437490312 {139921437069920}
139921437490312 {139921437070032}

```
I tried this:

```python
def _Commands(component):
    return _CommandsHelper(component)


def _CommandsHelper(component, seen=set()):
    seen.add(id(component))
    print(id(seen), seen)


_Commands("1")
_Commands("2")

_Commands("1")
_Commands("2")
```
result:

```
139851851967624 {139851851547232}
139851851967624 {139851851547232, 139851851547344}
139851851967624 {139851851547232, 139851851547344}
139851851967624 {139851851547232, 139851851547344}
```

The second result is what i want.

**Comment by dbieber** [comment]
I think the first of those two experiments is actually closer to what we want. Calling `_Command` multiple times should give the same result each time. It's _within_ a command that we want to avoid repeating component ids, since that's how we avoid the infinite loops I described.

I put together what I think is a complete implementation, though I haven't tested it:

```python
def _Commands(component, depth=3, avoid_cycles=True, used_ids=None):
  """Yields tuples representing commands for the component.
  
  Args:
    component: The component considered to be the root of the yielded commands.
    depth: The maximum depth with which to traverse the member DAG for commands.
        If depth is None, no depth constraints are imposed.
    used_ids: The set of the ids of the components already used in the command.
    avoid_cycles: If True, then commands will not repeat component ids they've
        already used.
  Yields:
    Tuples, each tuple representing one possible command for this component.
  """
  used_ids = used_ids or set()
  used_ids.add(id(component))

  if depth is not None and depth < 1:
    return
  next_depth = depth - 1 if depth is not None else None

  for member_name, member in _Members(component):
    if avoid_cycles and id(member) in used_ids:
      continue

    member_name = _FormatForCommand(member_name)
    yield (member_name,)
    
    if inspect.isroutine(member) or inspect.isclass(member):
      for completion in Completions(member):
        yield (member_name, completion)
      continue  # Don't descend into routines.
 
    for command in _Commands(member, used_ids, next_depth, avoid_cycles):
      yield (member_name,) + command
  
  used_ids.remove(id(component))
```

Calling `_Commands(component, depth=3, avoid_cycles=False)` should have the same behavior that the current `_Commands` implementation has, whereas calling `_Commands(component, depth=None, avoid_cycles=True)` should avoid repeating components within any command.

We'll have to add tests to verify this behavior before we're ready to check this or another implementation in.

What do you think?

**Comment by gaojiuli** [comment]
Alright, I agree with you！I will keep an eye on this project。

**Pull request closed without merging**
