### PR TITLE
WIP : Fix Part 1 of issue 51, uses os.path.basename(sys.argv[0])

### PR DESCRIPTION
**Pull request by saurabhkpatel**
Need help for creating the test case for this change.

### CODE REVIEW

**Comment by dbieber** [comment]
To test a specific argv you can use mock.patch as shown [here](https://github.com/google/python-fire/blob/master/fire/fire_test.py#L35).
`    with mock.patch.object(sys, 'argv', ['progname']):`

I would add the test to core_test.py, maybe as a second test after `testFire` named `testFireDefaultName`.
The test could use a filepath for sys.argv[0], include '--', '--trace' as args, and then do something like check that the basename shows up in the output.

**Comment by saurabhkpatel** [comment]
@dbieber  thanks for your suggestions :)
Never used mock in the python but this is the opportunity to learn from the community :)

I would write a new test method in core_test.py. My thoughts are similar like this.

```
  def testFireDefaultName(self):
    with mock.patch.object(sys, 'argv',
                           ['/github/python-fire/fire/base_filename.py']):
      output = fire.Fire(tc.Empty)
     assertIn("base_filename.py", output)    # would it work? 
```
I am not sure how to gather print output as return of `fire.Fire(tc.Empty)`.

Any suggestions?

**Comment by dbieber** [comment]
Once #54 is checked in you can use `with self.assertOutputMatches` to check the output of something like `fire.Fire(tc.Empty)`. That should be checked in ~tomorrow.

**Comment by dbieber** [comment]
^^ #54 is checked in now

**Comment by dbieber** [comment]
Closing. Superseded by #59.

**Pull request closed without merging**
