### PR TITLE
Fish completion support

### PR DESCRIPTION
**Pull request by Ellmen**
Re: https://github.com/google/python-fire/issues/56

This adds support for completions for the fish shell. It adds an optional argument to the --completions flag to specify a shell to create completions for.

Usage looks like:
`widget -- --completion` or `widget -- --completion bash`
for bash completions or
`widget -- --completion fish`
for fish completions

### CODE REVIEW

**Comment by dbieber** [comment]
Thanks for this contribution!
Props for your thoroughness with docs and tests :)

**Comment by dbieber** [comment]
Looking forward, we'd eventually like to replace our use of argparse in parser.py with fire.

When we do so, "completion" will become an argument of a function with default value 'None'. At that point '--completion' will be treated as `True`, '--completion bash' will be `'bash'`, and '--completion fish' will be `'fish'`. So, like in your code, we'll treat `True` as `'bash'`.

**Comment by Ellmen** [comment]
Happy to help! Sounds good - it should be relatively easy to add zsh support the same way

**Comment by dbieber** [comment]
That would be great -- #64 requests it.
I also welcome you to read the doc in #32 ([here](https://docs.google.com/document/d/1PvEK0nd_k3MxRjTuyH7lYvK4y4b2iYwickn2B56WomU/edit)) and let me know if you have thoughts on this or want to work on it.

**Pull request merged**
